server:
  port: 8221

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUurl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/