eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8221/eureka/

spring:
  application:
    name: service-zuul

server:
  port: 8226

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign